#if False == db["devmode"]:
    print("   --------        -----           -----     ")
    time.sleep(0.05)
    print("   |             /       \        /          ")
    time.sleep(0.05)
    print("   |            /         \      |           ")
    time.sleep(0.05)
    print("   |           |           |      \          ")
    time.sleep(0.05)
    print("   --------    |           |       -----     ")
    time.sleep(0.05)
    print("   |           |           |            \    ")
    time.sleep(0.05)
    print("   |            \         /              |   ")
    time.sleep(0.05)
    print("   |             \       /              /    ")
    time.sleep(0.05)
    print("   --------        -----           -----     ")
    time.sleep(0.5)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     \     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     -     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     /     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     |     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     \     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     -     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     /     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     |     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("  --------        -----           -----     ")
    print("  |             /       \        /          ")
    print("  |            /         \      |           ")
    print("  |           |           |      \          ")
    print("  --------    |     |     |       -----     ")
    print("  |           |           |            \    ")
    print("  |            \         /              |   ")
    print("  |             \       /              /    ")
    print("  --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print(" --------        -----           -----     ")
    print(" |             /       \        /          ")
    print(" |            /         \      |           ")
    print(" |           |           |      \          ")
    print(" --------    |     |     |       -----     ")
    print(" |           |           |            \    ")
    print(" |            \         /              |   ")
    print(" |             \       /              /    ")
    print(" --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("--------        -----           -----     ")
    print("|             /       \        /          ")
    print("|            /         \      |           ")
    print("|           |           |      \          ")
    print("--------    |     |     |       -----     ")
    print("|           |           |            \    ")
    print("|            \         /              |   ")
    print("|             \       /              /    ")
    print("--------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-------        -----           -----     ")
    print("             /       \        /          ")
    print("            /         \      |           ")
    print("           |           |      \          ")
    print("-------    |     |     |       -----     ")
    print("           |           |            \    ")
    print("            \         /              |   ")
    print("             \       /              /    ")
    print("-------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("------        -----           -----     ")
    print("            /       \        /          ")
    print("           /         \      |           ")
    print("          |           |      \          ")
    print("------    |     |     |       -----     ")
    print("          |           |            \    ")
    print("           \         /              |   ")
    print("            \       /              /    ")
    print("------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-----        -----           -----     ")
    print("           /       \        /          ")
    print("          /         \      |           ")
    print("         |           |      \          ")
    print("-----    |     \     |       -----     ")
    print("         |           |            \    ")
    print("          \         /              |   ")
    print("           \       /              /    ")
    print("-----        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("----        -----           -----     ")
    print("          /       \        /          ")
    print("         /         \      |           ")
    print("        |           |      \          ")
    print("----    |     \     |       -----     ")
    print("        |           |            \    ")
    print("         \         /              |   ")
    print("          \       /              /    ")
    print("----        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("---        -----           -----     ")
    print("         /       \        /          ")
    print("        /         \      |           ")
    print("       |           |      \          ")
    print("---    |     \     |       -----     ")
    print("       |           |            \    ")
    print("        \         /              |   ")
    print("         \       /              /    ")
    print("---        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("--        -----           -----     ")
    print("        /       \        /          ")
    print("       /         \      |           ")
    print("      |           |      \          ")
    print("--    |     \     |       -----     ")
    print("      |           |            \    ")
    print("       \         /              |   ")
    print("        \       /              /    ")
    print("--        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-        -----           -----     ")
    print("       /       \        /          ")
    print("      /         \      |           ")
    print("     |           |      \          ")
    print("-    |     \     |       -----     ")
    print("     |           |            \    ")
    print("      \         /              |   ")
    print("       \       /              /    ")
    print("-        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("        -----           -----     ")
    print("      /       \        /          ")
    print("     /         \      |           ")
    print("    |           |      \          ")
    print("    |     \     |       -----     ")
    print("    |           |            \    ")
    print("     \         /              |   ")
    print("      \       /              /    ")
    print("        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("       -----           -----     ")
    print("     /       \        /          ")
    print("    /         \      |           ")
    print("   |           |      \          ")
    print("   |     \     |       -----     ")
    print("   |           |            \    ")
    print("    \         /              |   ")
    print("     \       /              /    ")
    print("       -----           -----     ")
    time.sleep(0.025)
    clear()
    print("      -----           -----     ")
    print("    /       \        /          ")
    print("   /         \      |           ")
    print("  |           |      \          ")
    print("  |     -     |       -----     ")
    print("  |           |            \    ")
    print("   \         /              |   ")
    print("    \       /              /    ")
    print("      -----           -----     ")
    time.sleep(0.025)
    clear()
    print("     -----           -----     ")
    print("   /       \        /          ")
    print("  /         \      |           ")
    print(" |           |      \          ")
    print(" |     -     |       -----     ")
    print(" |           |            \    ")
    print("  \         /              |   ")
    print("   \       /              /    ")
    print("     -----           -----     ")
    time.sleep(0.025)
    clear()
    print("    -----           -----     ")
    print("  /       \        /          ")
    print(" /         \      |           ")
    print("|           |      \          ")
    print("|     -     |       -----     ")
    print("|           |            \    ")
    print(" \         /              |   ")
    print("  \       /              /    ")
    print("    -----           -----     ")
    time.sleep(0.025)
    clear()
    print("   -----           -----     ")
    print(" /       \        /          ")
    print("/         \      |           ")
    print("           |      \          ")
    print("     -     |       -----     ")
    print("           |            \    ")
    print("\         /              |   ")
    print(" \       /              /    ")
    print("   -----           -----     ")
    time.sleep(0.025)
    clear()
    print("  -----           -----     ")
    print("/       \        /          ")
    print("         \      |           ")
    print("          |      \          ")
    print("    -     |       -----     ")
    print("          |            \    ")
    print("         /              |   ")
    print("\       /              /    ")
    print("  -----           -----     ")
    time.sleep(0.025)
    clear()
    print(" -----           -----     ")
    print("       \        /          ")
    print("        \      |           ")
    print("         |      \          ")
    print("   -     |       -----     ")
    print("         |            \    ")
    print("        /              |   ")
    print("       /              /    ")
    print(" -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-----           -----     ")
    print("      \        /          ")
    print("       \      |           ")
    print("        |      \          ")
    print("  -     |       -----     ")
    print("        |            \    ")
    print("       /              |   ")
    print("      /              /    ")
    print("-----           -----     ")
    time.sleep(0.025)
    clear()
    print("----           -----     ")
    print("     \        /          ")
    print("      \      |           ")
    print("       |      \          ")
    print(" /     |       -----     ")
    print("       |            \    ")
    print("      /              |   ")
    print("     /              /    ")
    print("----           -----     ")
    time.sleep(0.025)
    clear()
    print("---           -----     ")
    print("    \        /          ")
    print("     \      |           ")
    print("      |      \          ")
    print("/     |       -----     ")
    print("      |            \    ")
    print("     /              |   ")
    print("    /              /    ")
    print("---           -----     ")
    time.sleep(0.025)
    clear()
    print("--           -----     ")
    print("   \        /          ")
    print("    \      |           ")
    print("     |      \          ")
    print("     |       -----     ")
    print("     |            \    ")
    print("    /              |   ")
    print("   /              /    ")
    print("--           -----     ")
    time.sleep(0.025)
    clear()
    print("-           -----     ")
    print("  \        /          ")
    print("   \      |           ")
    print("    |      \          ")
    print("    |       -----     ")
    print("    |            \    ")
    print("   /              |   ")
    print("  /              /    ")
    print("-           -----     ")
    time.sleep(0.025)
    clear()
    print("           -----     ")
    print(" \        /          ")
    print("  \      |           ")
    print("   |      \          ")
    print("   |       -----     ")
    print("   |            \    ")
    print("  /              |   ")
    print(" /              /    ")
    print("           -----     ")
    time.sleep(0.025)
    clear()
    print("          -----     ")
    print("\        /          ")
    print(" \      |           ")
    print("  |      \          ")
    print("  |       -----     ")
    print("  |            \    ")
    print(" /              |   ")
    print("/              /    ")
    print("          -----     ")
    time.sleep(0.025)
    clear()
    print("         -----     ")
    print("        /          ")
    print("\      |           ")
    print(" |      \          ")
    print(" |       -----     ")
    print(" |            \    ")
    print("/              |   ")
    print("              /    ")
    print("         -----     ")
    time.sleep(0.025)
    clear()
    print("        -----     ")
    print("       /          ")
    print("      |           ")
    print("|      \          ")
    print("|       -----     ")
    print("|            \    ")
    print("              |   ")
    print("             /    ")
    print("        -----     ")
    time.sleep(0.025)
    clear()
    print("       -----     ")
    print("      /          ")
    print("     |           ")
    print("      \          ")
    print("       -----     ")
    print("            \    ")
    print("             |   ")
    print("            /    ")
    print("       -----     ")
    time.sleep(0.025)
    clear()
    print("      -----     ")
    print("     /          ")
    print("    |           ")
    print("     \          ")
    print("      -----     ")
    print("           \    ")
    print("            |   ")
    print("           /    ")
    print("      -----     ")
    time.sleep(0.025)
    clear()
    print("     -----     ")
    print("    /          ")
    print("   |           ")
    print("    \          ")
    print("     -----     ")
    print("          \    ")
    print("           |   ")
    print("          /    ")
    print("     -----     ")
    time.sleep(0.025)
    clear()
    print("    -----     ")
    print("   /          ")
    print("  |           ")
    print("   \          ")
    print("    -----     ")
    print("         \    ")
    print("          |   ")
    print("         /    ")
    print("    -----     ")
    time.sleep(0.025)
    clear()
    print("   -----     ")
    print("  /          ")
    print(" |           ")
    print("  \          ")
    print("   -----     ")
    print("        \    ")
    print("         |   ")
    print("        /    ")
    print("   -----     ")
    time.sleep(0.025)
    clear()
    print("  -----     ")
    print(" /          ")
    print("|           ")
    print(" \          ")
    print("  -----     ")
    print("       \    ")
    print("        |   ")
    print("       /    ")
    print("  -----     ")
    time.sleep(0.025)
    clear()
    print(" -----     ")
    print("/          ")
    print("           ")
    print("\          ")
    print(" -----     ")
    print("      \    ")
    print("       |   ")
    print("      /    ")
    print(" -----     ")
    time.sleep(0.025)
    clear()
    print("-----     ")
    print("          ")
    print("          ")
    print("          ")
    print("-----     ")
    print("     \    ")
    print("      |   ")
    print("     /    ")
    print("-----     ")
    time.sleep(0.025)
    clear()
    print("----     ")
    print("         ")
    print("         ")
    print("         ")
    print("----     ")
    print("    \    ")
    print("     |   ")
    print("    /    ")
    print("----     ")
    time.sleep(0.025)
    clear()
    print("---     ")
    print("        ")
    print("        ")
    print("        ")
    print("---     ")
    print("   \    ")
    print("    |   ")
    print("   /    ")
    print("---     ")
    time.sleep(0.025)
    clear()
    print("--     ")
    print("       ")
    print("       ")
    print("       ")
    print("--     ")
    print("  \    ")
    print("   |   ")
    print("  /    ")
    print("--     ")
    time.sleep(0.025)
    clear()
    print("-     ")
    print("      ")
    print("      ")
    print("      ")
    print("-     ")
    print(" \    ")
    print("  |   ")
    print(" /    ")
    print("-     ")
    time.sleep(0.025)
    clear()
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("\    ")
    print(" |   ")
    print("/    ")
    print("     ")
    time.sleep(0.025)
    clear()
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("|   ")
    print("    ")
    print("    ")