import time
from os import system
from replit import db
def clear():
  system('clear')
print("   --------        -----           -----     ")
time.sleep(0.05)
print("   |             /       \        /          ")
time.sleep(0.05)
print("   |            /         \      |           ")
time.sleep(0.05)
print("   |           |           |      \          ")
time.sleep(0.05)
print("   --------    |           |       -----     ")
time.sleep(0.05)
print("   |           |           |            \    ")
time.sleep(0.05)
print("   |            \         /              |   ")
time.sleep(0.05)
print("   |             \       /              /    ")
time.sleep(0.05)
print("   --------        -----           -----     ")
time.sleep(0.5)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     \     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     -     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     /     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     |     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     \     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     -     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     /     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.15)
clear()
print("   --------        -----           -----     ")
print("   |             /       \        /          ")
print("   |            /         \      |           ")
print("   |           |           |      \          ")
print("   --------    |     |     |       -----     ")
print("   |           |           |            \    ")
print("   |            \         /              |   ")
print("   |             \       /              /    ")
print("   --------        -----           -----     ")
time.sleep(0.025)
clear()
print("  --------        -----           -----     ")
print("  |             /       \        /          ")
print("  |            /         \      |           ")
print("  |           |           |      \          ")
print("  --------    |     |     |       -----     ")
print("  |           |           |            \    ")
print("  |            \         /              |   ")
print("  |             \       /              /    ")
print("  --------        -----           -----     ")
time.sleep(0.025)
clear()
print(" --------        -----           -----     ")
print(" |             /       \        /          ")
print(" |            /         \      |           ")
print(" |           |           |      \          ")
print(" --------    |     |     |       -----     ")
print(" |           |           |            \    ")
print(" |            \         /              |   ")
print(" |             \       /              /    ")
print(" --------        -----           -----     ")
time.sleep(0.025)
clear()
print("--------        -----           -----     ")
print("|             /       \        /          ")
print("|            /         \      |           ")
print("|           |           |      \          ")
print("--------    |     |     |       -----     ")
print("|           |           |            \    ")
print("|            \         /              |   ")
print("|             \       /              /    ")
print("--------        -----           -----     ")
time.sleep(0.025)
clear()
print("-------        -----           -----     ")
print("             /       \        /          ")
print("            /         \      |           ")
print("           |           |      \          ")
print("-------    |     |     |       -----     ")
print("           |           |            \    ")
print("            \         /              |   ")
print("             \       /              /    ")
print("-------        -----           -----     ")
time.sleep(0.025)
clear()
print("------        -----           -----     ")
print("            /       \        /          ")
print("           /         \      |           ")
print("          |           |      \          ")
print("------    |     |     |       -----     ")
print("          |           |            \    ")
print("           \         /              |   ")
print("            \       /              /    ")
print("------        -----           -----     ")
time.sleep(0.025)
clear()
print("-----        -----           -----     ")
print("           /       \        /          ")
print("          /         \      |           ")
print("         |           |      \          ")
print("-----    |     \     |       -----     ")
print("         |           |            \    ")
print("          \         /              |   ")
print("           \       /              /    ")
print("-----        -----           -----     ")
time.sleep(0.025)
clear()
print("----        -----           -----     ")
print("          /       \        /          ")
print("         /         \      |           ")
print("        |           |      \          ")
print("----    |     \     |       -----     ")
print("        |           |            \    ")
print("         \         /              |   ")
print("          \       /              /    ")
print("----        -----           -----     ")
time.sleep(0.025)
clear()
print("---        -----           -----     ")
print("         /       \        /          ")
print("        /         \      |           ")
print("       |           |      \          ")
print("---    |     \     |       -----     ")
print("       |           |            \    ")
print("        \         /              |   ")
print("         \       /              /    ")
print("---        -----           -----     ")
time.sleep(0.025)
clear()
print("--        -----           -----     ")
print("        /       \        /          ")
print("       /         \      |           ")
print("      |           |      \          ")
print("--    |     \     |       -----     ")
print("      |           |            \    ")
print("       \         /              |   ")
print("        \       /              /    ")
print("--        -----           -----     ")
time.sleep(0.025)
clear()
print("-        -----           -----     ")
print("       /       \        /          ")
print("      /         \      |           ")
print("     |           |      \          ")
print("-    |     \     |       -----     ")
print("     |           |            \    ")
print("      \         /              |   ")
print("       \       /              /    ")
print("-        -----           -----     ")
time.sleep(0.15)
clear()
print("        -----           -----     ")
print("      /       \        /          ")
print("     /         \      |           ")
print("    |           |      \          ")
print("    |     \     |       -----     ")
print("    |           |            \    ")
print("     \         /              |   ")
print("      \       /              /    ")
print("        -----           -----     ")
time.sleep(0.025)
clear()
print("       -----           -----     ")
print("     /       \        /          ")
print("    /         \      |           ")
print("   |           |      \          ")
print("   |     \     |       -----     ")
print("   |           |            \    ")
print("    \         /              |   ")
print("     \       /              /    ")
print("       -----           -----     ")
time.sleep(0.025)
clear()
print("      -----           -----     ")
print("    /       \        /          ")
print("   /         \      |           ")
print("  |           |      \          ")
print("  |     -     |       -----     ")
print("  |           |            \    ")
print("   \         /              |   ")
print("    \       /              /    ")
print("      -----           -----     ")
time.sleep(0.025)
clear()
print("     -----           -----     ")
print("   /       \        /          ")
print("  /         \      |           ")
print(" |           |      \          ")
print(" |     -     |       -----     ")
print(" |           |            \    ")
print("  \         /              |   ")
print("   \       /              /    ")
print("     -----           -----     ")
time.sleep(0.025)
clear()
print("    -----           -----     ")
print("  /       \        /          ")
print(" /         \      |           ")
print("|           |      \          ")
print("|     -     |       -----     ")
print("|           |            \    ")
print(" \         /              |   ")
print("  \       /              /    ")
print("    -----           -----     ")
time.sleep(0.025)
clear()
print("   -----           -----     ")
print(" /       \        /          ")
print("/         \      |           ")
print("           |      \          ")
print("     -     |       -----     ")
print("           |            \    ")
print("\         /              |   ")
print(" \       /              /    ")
print("   -----           -----     ")
time.sleep(0.025)
clear()
print("  -----           -----     ")
print("/       \        /          ")
print("         \      |           ")
print("          |      \          ")
print("    -     |       -----     ")
print("          |            \    ")
print("         /              |   ")
print("\       /              /    ")
print("  -----           -----     ")
time.sleep(0.025)
clear()
print(" -----           -----     ")
print("       \        /          ")
print("        \      |           ")
print("         |      \          ")
print("   -     |       -----     ")
print("         |            \    ")
print("        /              |   ")
print("       /              /    ")
print(" -----           -----     ")
time.sleep(0.025)
clear()
print("-----           -----     ")
print("      \        /          ")
print("       \      |           ")
print("        |      \          ")
print("  -     |       -----     ")
print("        |            \    ")
print("       /              |   ")
print("      /              /    ")
print("-----           -----     ")
time.sleep(0.025)
clear()
print("----           -----     ")
print("     \        /          ")
print("      \      |           ")
print("       |      \          ")
print(" /     |       -----     ")
print("       |            \    ")
print("      /              |   ")
print("     /              /    ")
print("----           -----     ")
time.sleep(0.025)
clear()
print("---           -----     ")
print("    \        /          ")
print("     \      |           ")
print("      |      \          ")
print("/     |       -----     ")
print("      |            \    ")
print("     /              |   ")
print("    /              /    ")
print("---           -----     ")
time.sleep(0.025)
clear()
print("--           -----     ")
print("   \        /          ")
print("    \      |           ")
print("     |      \          ")
print("     |       -----     ")
print("     |            \    ")
print("    /              |   ")
print("   /              /    ")
print("--           -----     ")
time.sleep(0.025)
clear()
print("-           -----     ")
print("  \        /          ")
print("   \      |           ")
print("    |      \          ")
print("    |       -----     ")
print("    |            \    ")
print("   /              |   ")
print("  /              /    ")
print("-           -----     ")
time.sleep(0.025)
clear()
print("           -----     ")
print(" \        /          ")
print("  \      |           ")
print("   |      \          ")
print("   |       -----     ")
print("   |            \    ")
print("  /              |   ")
print(" /              /    ")
print("           -----     ")
time.sleep(0.025)
clear()
print("          -----     ")
print("\        /          ")
print(" \      |           ")
print("  |      \          ")
print("  |       -----     ")
print("  |            \    ")
print(" /              |   ")
print("/              /    ")
print("          -----     ")
time.sleep(0.025)
clear()
print("         -----     ")
print("        /          ")
print("\      |           ")
print(" |      \          ")
print(" |       -----     ")
print(" |            \    ")
print("/              |   ")
print("              /    ")
print("         -----     ")
time.sleep(0.025)
clear()
print("        -----     ")
print("       /          ")
print("      |           ")
print("|      \          ")
print("|       -----     ")
print("|            \    ")
print("              |   ")
print("             /    ")
print("        -----     ")
time.sleep(0.025)
clear()
print("       -----     ")
print("      /          ")
print("     |           ")
print("      \          ")
print("       -----     ")
print("            \    ")
print("             |   ")
print("            /    ")
print("       -----     ")
time.sleep(0.025)
clear()
print("      -----     ")
print("     /          ")
print("    |           ")
print("     \          ")
print("      -----     ")
print("           \    ")
print("            |   ")
print("           /    ")
print("      -----     ")
time.sleep(0.025)
clear()
print("     -----     ")
print("    /          ")
print("   |           ")
print("    \          ")
print("     -----     ")
print("          \    ")
print("           |   ")
print("          /    ")
print("     -----     ")
time.sleep(0.025)
clear()
print("    -----     ")
print("   /          ")
print("  |           ")
print("   \          ")
print("    -----     ")
print("         \    ")
print("          |   ")
print("         /    ")
print("    -----     ")
time.sleep(0.025)
clear()
print("   -----     ")
print("  /          ")
print(" |           ")
print("  \          ")
print("   -----     ")
print("        \    ")
print("         |   ")
print("        /    ")
print("   -----     ")
time.sleep(0.025)
clear()
print("  -----     ")
print(" /          ")
print("|           ")
print(" \          ")
print("  -----     ")
print("       \    ")
print("        |   ")
print("       /    ")
print("  -----     ")
time.sleep(0.025)
clear()
print(" -----     ")
print("/          ")
print("           ")
print("\          ")
print(" -----     ")
print("      \    ")
print("       |   ")
print("      /    ")
print(" -----     ")
time.sleep(0.025)
clear()
print("-----     ")
print("          ")
print("          ")
print("          ")
print("-----     ")
print("     \    ")
print("      |   ")
print("     /    ")
print("-----     ")
time.sleep(0.025)
clear()
print("----     ")
print("         ")
print("         ")
print("         ")
print("----     ")
print("    \    ")
print("     |   ")
print("    /    ")
print("----     ")
time.sleep(0.025)
clear()
print("---     ")
print("        ")
print("        ")
print("        ")
print("---     ")
print("   \    ")
print("    |   ")
print("   /    ")
print("---     ")
time.sleep(0.025)
clear()
print("--     ")
print("       ")
print("       ")
print("       ")
print("--     ")
print("  \    ")
print("   |   ")
print("  /    ")
print("--     ")
time.sleep(0.025)
clear()
print("-     ")
print("      ")
print("      ")
print("      ")
print("-     ")
print(" \    ")
print("  |   ")
print(" /    ")
print("-     ")
time.sleep(0.025)
clear()
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print("\    ")
print(" |   ")
print("/    ")
print("     ")
time.sleep(0.025)
clear()
print("    ")
print("    ")
print("    ")
print("    ")
print("    ")
print("    ")
print("|   ")
print("    ")
print("    ")
exec(open("main.py").read())