import time
from os import system
loaded = False
usrinapp = 0
with open("test.txt") as f:
  lines = f.readlines()
def clear():
  system('clear')

def main():
  clear()
  #Home screen
  print("EOS 1.1.0")
  print("Build 1")
  print()
  print("-------------------------- ")
  print("Applications:              ")
  print("  >Games:                  ")
  print("    1.0 - Shooter          ")
  print("    1.1 - YMegle           ")
  print("  >Utilities:              ")
  print("    2.0 - Calculator       ")
  print("    2.1 - Dictionary       ")
  print("    2.2 - Power options    ")
  print("                           ")
  print("  4 - Credits              ")
  print("-------------------------- ")
  print()
  #Ask the user to input a number
  print("Input a number corresponding to the            ")
  usrinapp = input("application you would like to run:  ")
  
  #Launch apps
  if usrinapp == "t":
    usrinapp = 0
    clear()
    exec(open("turtleUI.py").read())
    quit()
  #1.0 - Shooter
  if usrinapp == "1.0":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Games/Shooter/shootermain.py").read())
    quit()
  #1.1 - YMegle
  if usrinapp == "1.1":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Games/YMegle/ymegle.py").read())
    quit()
  #2.0 - Calculator
  if usrinapp == "2.0":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Utilities/Calculator/calcmain.py").read())
    quit()
  #2.1 - Dictionary
  if usrinapp == "2.1":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Utilities/Dictionary/dictmain.py").read())
    quit()
  #2.2 - Power options (Shutdown/Restart)
  if usrinapp == "2.2":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Utilities/Power_options/pwoptmain.py").read())
    quit()
  #4 - Credits
  if usrinapp == "4":
    #Reset usrinapp and clear the screen
    usrinapp = 0
    clear()
    exec(open("Apps/Utilities/Credits/creditmain.py").read())
    quit()
  else:
    clear()
    print("---------------------")
    print("Error 404: Could not find application")
    print("---------------------")
    time.sleep(1.5)
    clear()
    main()
def loading():
  clear()
  if lines == ['False']:
    clear()
    time.sleep(2)
    print("America Megatrends")
    print("BIOS VERSION 0.5.0 ")
    time.sleep(1)
    print("OS Detected, Loading EOS...")
    time.sleep(0.5)
    print("   --------        -----           -----     ")
    time.sleep(0.05)
    print("   |             /       \        /          ")
    time.sleep(0.05)
    print("   |            /         \      |           ")
    time.sleep(0.05)
    print("   |           |           |      \          ")
    time.sleep(0.05)
    print("   --------    |           |       -----     ")
    time.sleep(0.05)
    print("   |           |           |            \    ")
    time.sleep(0.05)
    print("   |            \         /              |   ")
    time.sleep(0.05)
    print("   |             \       /              /    ")
    time.sleep(0.05)
    print("   --------        -----           -----     ")
    time.sleep(0.5)
    print("")
    print("")
    print("")
    print("")
    print("")
    print("EOS Version 1.2.0 Dev")
    time.sleep(1)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     \     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     -     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     /     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     |     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     \     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     -     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     /     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("   --------        -----           -----     ")
    print("   |             /       \        /          ")
    print("   |            /         \      |           ")
    print("   |           |           |      \          ")
    print("   --------    |     |     |       -----     ")
    print("   |           |           |            \    ")
    print("   |            \         /              |   ")
    print("   |             \       /              /    ")
    print("   --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("  --------        -----           -----     ")
    print("  |             /       \        /          ")
    print("  |            /         \      |           ")
    print("  |           |           |      \          ")
    print("  --------    |     |     |       -----     ")
    print("  |           |           |            \    ")
    print("  |            \         /              |   ")
    print("  |             \       /              /    ")
    print("  --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print(" --------        -----           -----     ")
    print(" |             /       \        /          ")
    print(" |            /         \      |           ")
    print(" |           |           |      \          ")
    print(" --------    |     |     |       -----     ")
    print(" |           |           |            \    ")
    print(" |            \         /              |   ")
    print(" |             \       /              /    ")
    print(" --------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("--------        -----           -----     ")
    print("|             /       \        /          ")
    print("|            /         \      |           ")
    print("|           |           |      \          ")
    print("--------    |     |     |       -----     ")
    print("|           |           |            \    ")
    print("|            \         /              |   ")
    print("|             \       /              /    ")
    print("--------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-------        -----           -----     ")
    print("             /       \        /          ")
    print("            /         \      |           ")
    print("           |           |      \          ")
    print("-------    |     |     |       -----     ")
    print("           |           |            \    ")
    print("            \         /              |   ")
    print("             \       /              /    ")
    print("-------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("------        -----           -----     ")
    print("            /       \        /          ")
    print("           /         \      |           ")
    print("          |           |      \          ")
    print("------    |     |     |       -----     ")
    print("          |           |            \    ")
    print("           \         /              |   ")
    print("            \       /              /    ")
    print("------        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-----        -----           -----     ")
    print("           /       \        /          ")
    print("          /         \      |           ")
    print("         |           |      \          ")
    print("-----    |     \     |       -----     ")
    print("         |           |            \    ")
    print("          \         /              |   ")
    print("           \       /              /    ")
    print("-----        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("----        -----           -----     ")
    print("          /       \        /          ")
    print("         /         \      |           ")
    print("        |           |      \          ")
    print("----    |     \     |       -----     ")
    print("        |           |            \    ")
    print("         \         /              |   ")
    print("          \       /              /    ")
    print("----        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("---        -----           -----     ")
    print("         /       \        /          ")
    print("        /         \      |           ")
    print("       |           |      \          ")
    print("---    |     \     |       -----     ")
    print("       |           |            \    ")
    print("        \         /              |   ")
    print("         \       /              /    ")
    print("---        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("--        -----           -----     ")
    print("        /       \        /          ")
    print("       /         \      |           ")
    print("      |           |      \          ")
    print("--    |     \     |       -----     ")
    print("      |           |            \    ")
    print("       \         /              |   ")
    print("        \       /              /    ")
    print("--        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-        -----           -----     ")
    print("       /       \        /          ")
    print("      /         \      |           ")
    print("     |           |      \          ")
    print("-    |     \     |       -----     ")
    print("     |           |            \    ")
    print("      \         /              |   ")
    print("       \       /              /    ")
    print("-        -----           -----     ")
    time.sleep(0.15)
    clear()
    print("        -----           -----     ")
    print("      /       \        /          ")
    print("     /         \      |           ")
    print("    |           |      \          ")
    print("    |     \     |       -----     ")
    print("    |           |            \    ")
    print("     \         /              |   ")
    print("      \       /              /    ")
    print("        -----           -----     ")
    time.sleep(0.025)
    clear()
    print("       -----           -----     ")
    print("     /       \        /          ")
    print("    /         \      |           ")
    print("   |           |      \          ")
    print("   |     \     |       -----     ")
    print("   |           |            \    ")
    print("    \         /              |   ")
    print("     \       /              /    ")
    print("       -----           -----     ")
    time.sleep(0.025)
    clear()
    print("      -----           -----     ")
    print("    /       \        /          ")
    print("   /         \      |           ")
    print("  |           |      \          ")
    print("  |     -     |       -----     ")
    print("  |           |            \    ")
    print("   \         /              |   ")
    print("    \       /              /    ")
    print("      -----           -----     ")
    time.sleep(0.025)
    clear()
    print("     -----           -----     ")
    print("   /       \        /          ")
    print("  /         \      |           ")
    print(" |           |      \          ")
    print(" |     -     |       -----     ")
    print(" |           |            \    ")
    print("  \         /              |   ")
    print("   \       /              /    ")
    print("     -----           -----     ")
    time.sleep(0.025)
    clear()
    print("    -----           -----     ")
    print("  /       \        /          ")
    print(" /         \      |           ")
    print("|           |      \          ")
    print("|     -     |       -----     ")
    print("|           |            \    ")
    print(" \         /              |   ")
    print("  \       /              /    ")
    print("    -----           -----     ")
    time.sleep(0.025)
    clear()
    print("   -----           -----     ")
    print(" /       \        /          ")
    print("/         \      |           ")
    print("           |      \          ")
    print("     -     |       -----     ")
    print("           |            \    ")
    print("\         /              |   ")
    print(" \       /              /    ")
    print("   -----           -----     ")
    time.sleep(0.025)
    clear()
    print("  -----           -----     ")
    print("/       \        /          ")
    print("         \      |           ")
    print("          |      \          ")
    print("    -     |       -----     ")
    print("          |            \    ")
    print("         /              |   ")
    print("\       /              /    ")
    print("  -----           -----     ")
    time.sleep(0.025)
    clear()
    print(" -----           -----     ")
    print("       \        /          ")
    print("        \      |           ")
    print("         |      \          ")
    print("   -     |       -----     ")
    print("         |            \    ")
    print("        /              |   ")
    print("       /              /    ")
    print(" -----           -----     ")
    time.sleep(0.025)
    clear()
    print("-----           -----     ")
    print("      \        /          ")
    print("       \      |           ")
    print("        |      \          ")
    print("  -     |       -----     ")
    print("        |            \    ")
    print("       /              |   ")
    print("      /              /    ")
    print("-----           -----     ")
    time.sleep(0.025)
    clear()
    print("----           -----     ")
    print("     \        /          ")
    print("      \      |           ")
    print("       |      \          ")
    print(" /     |       -----     ")
    print("       |            \    ")
    print("      /              |   ")
    print("     /              /    ")
    print("----           -----     ")
    time.sleep(0.025)
    clear()
    print("---           -----     ")
    print("    \        /          ")
    print("     \      |           ")
    print("      |      \          ")
    print("/     |       -----     ")
    print("      |            \    ")
    print("     /              |   ")
    print("    /              /    ")
    print("---           -----     ")
    time.sleep(0.025)
    clear()
    print("--           -----     ")
    print("   \        /          ")
    print("    \      |           ")
    print("     |      \          ")
    print("     |       -----     ")
    print("     |            \    ")
    print("    /              |   ")
    print("   /              /    ")
    print("--           -----     ")
    time.sleep(0.025)
    clear()
    print("-           -----     ")
    print("  \        /          ")
    print("   \      |           ")
    print("    |      \          ")
    print("    |       -----     ")
    print("    |            \    ")
    print("   /              |   ")
    print("  /              /    ")
    print("-           -----     ")
    time.sleep(0.025)
    clear()
    print("           -----     ")
    print(" \        /          ")
    print("  \      |           ")
    print("   |      \          ")
    print("   |       -----     ")
    print("   |            \    ")
    print("  /              |   ")
    print(" /              /    ")
    print("           -----     ")
    time.sleep(0.025)
    clear()
    print("          -----     ")
    print("\        /          ")
    print(" \      |           ")
    print("  |      \          ")
    print("  |       -----     ")
    print("  |            \    ")
    print(" /              |   ")
    print("/              /    ")
    print("          -----     ")
    time.sleep(0.025)
    clear()
    print("         -----     ")
    print("        /          ")
    print("\      |           ")
    print(" |      \          ")
    print(" |       -----     ")
    print(" |            \    ")
    print("/              |   ")
    print("              /    ")
    print("         -----     ")
    time.sleep(0.025)
    clear()
    print("        -----     ")
    print("       /          ")
    print("      |           ")
    print("|      \          ")
    print("|       -----     ")
    print("|            \    ")
    print("              |   ")
    print("             /    ")
    print("        -----     ")
    time.sleep(0.025)
    clear()
    print("       -----     ")
    print("      /          ")
    print("     |           ")
    print("      \          ")
    print("       -----     ")
    print("            \    ")
    print("             |   ")
    print("            /    ")
    print("       -----     ")
    time.sleep(0.025)
    clear()
    print("      -----     ")
    print("     /          ")
    print("    |           ")
    print("     \          ")
    print("      -----     ")
    print("           \    ")
    print("            |   ")
    print("           /    ")
    print("      -----     ")
    time.sleep(0.025)
    clear()
    print("     -----     ")
    print("    /          ")
    print("   |           ")
    print("    \          ")
    print("     -----     ")
    print("          \    ")
    print("           |   ")
    print("          /    ")
    print("     -----     ")
    time.sleep(0.025)
    clear()
    print("    -----     ")
    print("   /          ")
    print("  |           ")
    print("   \          ")
    print("    -----     ")
    print("         \    ")
    print("          |   ")
    print("         /    ")
    print("    -----     ")
    time.sleep(0.025)
    clear()
    print("   -----     ")
    print("  /          ")
    print(" |           ")
    print("  \          ")
    print("   -----     ")
    print("        \    ")
    print("         |   ")
    print("        /    ")
    print("   -----     ")
    time.sleep(0.025)
    clear()
    print("  -----     ")
    print(" /          ")
    print("|           ")
    print(" \          ")
    print("  -----     ")
    print("       \    ")
    print("        |   ")
    print("       /    ")
    print("  -----     ")
    time.sleep(0.025)
    clear()
    print(" -----     ")
    print("/          ")
    print("           ")
    print("\          ")
    print(" -----     ")
    print("      \    ")
    print("       |   ")
    print("      /    ")
    print(" -----     ")
    time.sleep(0.025)
    clear()
    print("-----     ")
    print("          ")
    print("          ")
    print("          ")
    print("-----     ")
    print("     \    ")
    print("      |   ")
    print("     /    ")
    print("-----     ")
    time.sleep(0.025)
    clear()
    print("----     ")
    print("         ")
    print("         ")
    print("         ")
    print("----     ")
    print("    \    ")
    print("     |   ")
    print("    /    ")
    print("----     ")
    time.sleep(0.025)
    clear()
    print("---     ")
    print("        ")
    print("        ")
    print("        ")
    print("---     ")
    print("   \    ")
    print("    |   ")
    print("   /    ")
    print("---     ")
    time.sleep(0.025)
    clear()
    print("--     ")
    print("       ")
    print("       ")
    print("       ")
    print("--     ")
    print("  \    ")
    print("   |   ")
    print("  /    ")
    print("--     ")
    time.sleep(0.025)
    clear()
    print("-     ")
    print("      ")
    print("      ")
    print("      ")
    print("-     ")
    print(" \    ")
    print("  |   ")
    print(" /    ")
    print("-     ")
    time.sleep(0.025)
    clear()
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("     ")
    print("\    ")
    print(" |   ")
    print("/    ")
    print("     ")
    time.sleep(0.025)
    clear()
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("    ")
    print("|   ")
    print("    ")
    print("    ")
    with open("test.txt", "w") as g:
      g.write("True")
    main()
  elif lines == ['True']:
    print("Loaded")
    main()
  else:
    print("Error 100: Illegal Loading Status")
    print(lines)
loading()
    
    
