print("Loading credits...")
print("Importing:        ")
print("  time            ")
import time

print("EOS-----------------------")
print("  Original creator: Ewoud ")
print("  Co-Creator: Yifei       ")
print("  Started 10/4/2022       ")
time.sleep(2)
print("Egg-----------------------")
print("  Creator: Ewoud          ")
print("  Started 4/6/2017        ")
time.sleep(2)
print("Calculator----------------")
print("  Creator: Ewoud          ")
print("  Started 10/14/2022      ")
time.sleep(2)
print("Dictionary----------------")
print("  Creator: Ewoud          ")
print("  Library: PyDictionary   ")
print("  Started 10/24/2022      ")
print("--------------------------")
    
print("Returning Home in a few seconds...")
time.sleep(3)
exec(open("main.py").read())